import "./globals.css";
import {NavigationBar} from "@/components/NavigationBar/NavigationBar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body>
            <NavigationBar/>
            {children}
        </body>
    </html>
  );
}
